### ISSUE TITLE
Error while converting charmm format to GROMACS format

### ISSUE THREAD

**Issue by praveen950** [pritampanda15/Molecular-Dynamics#1]
I followed your youtube tutorials on MD simulations and faced an error as follows:-
$ python cgneff_charmm2gmx_py3_nx2.py UNL ligand_fixed.mol2 UNL.str charmm36-feb2021.ff
Command 'python' not found, did you mean:
     command 'python3' from deb python3
     command 'python' from deb python-is-python3
$ python3 cgneff_charmm2gmx_py3_nx2.py UNL ligand_fixed.mol2 UNL.str charmm36-feb2021.ff
python3: can't open file '/home/mallari/Desktop/MD1/MD1/cgneff_charmm2gmx_py3_nx2.py' : [Errno 2] No such file or directory

**Comment by pritampanda15** [comment]
This is just a very basic error that you get. Your file is located somewhere else.
